name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies and build the library
        uses: actions/checkout@v2
        run: |
          yarn
          yarn prepack
      - name: Validate TypeScript definitions
        run: yarn test:types
